# Global LLM configuration
[llm]
# Default LLM provider (choose: anthropic, openai, azure_openai, gemini, deepseek)
provider = "anthropic"
# Model and endpoint for each provider
[llm.anthropic]
model = "claude-3-7-sonnet-20250219"
base_url = "https://api.anthropic.com/v1/"
api_key = "${Anthropic}"
max_tokens = 1000000
temperature = 0.0

[llm.openai]
model = "gpt-4o"
base_url = "https://api.openai.com/v1/"
api_key = "${OpenAI}"
max_tokens = 1000000
temperature = 0.0

[llm.azure_openai]
model = "gpt-4o"
base_url = "https://YOUR_AZURE_ENDPOINT/openai/deployments/YOUR_DEPLOYMENT_ID"
api_key = "${Azure OpenAI}"
api_version = "2024-08-01-preview"
max_tokens = 1000000
temperature = 0.0

[llm.gemini]
model = "gemini-1.5-pro"
base_url = "https://generativelanguage.googleapis.com/v1beta"
api_key = "${Gemini}"
max_tokens = 1000000
temperature = 0.0

[llm.deepseek]
model = "deepseek-chat"
base_url = "https://api.deepseek.com/v1/"
api_key = "${DeepSeek}"
max_tokens = 1000000
temperature = 0.0

# The config loader should read API keys from keys.txt in the format:
# OpenAI=openai_api_key
# Anthropic=anthropic_api_key
# Azure OpenAI=azure_openai_api_key
# Gemini=gemini_api_key
# DeepSeek=deepseek_api_key
#
# [WSL/AUTONOMOUS MODE]
# To enable autonomous operation in WSL, ensure your agent mode is enabled (see main_Version2.py --agent)
# and that your API key and model support long context windows (unlimited tokens).
#



# [llm] #AZURE OPENAI:
# api_type= 'azure'
# model = "YOUR_MODEL_NAME" #"gpt-4o-mini"
# base_url = "{YOUR_AZURE_ENDPOINT.rstrip('/')}/openai/deployments/{AZURE_DEPLOYMENT_ID}"
# api_key = "AZURE API KEY"
# max_tokens = 8096
# temperature = 0.0
# api_version="AZURE API VERSION" #"2024-08-01-preview"

# [llm] #OLLAMA:
# api_type = 'ollama'
# model = "llama3.2"
# base_url = "http://localhost:11434/v1"
# api_key = "ollama"
# max_tokens = 4096
# temperature = 0.0

# Optional configuration for specific LLM models
[llm.vision]
model = "claude-3-7-sonnet-20250219"       # The vision model to use
base_url = "https://api.anthropic.com/v1/" # API endpoint URL for vision model
api_key = "YOUR_API_KEY"                   # Your API key for vision model
max_tokens = 8192                          # Maximum number of tokens in the response
temperature = 0.0                          # Controls randomness for vision model

# [llm.vision] #OLLAMA VISION:
# api_type = 'ollama'
# model = "llama3.2-vision"
# base_url = "http://localhost:11434/v1"
# api_key = "ollama"
# max_tokens = 4096
# temperature = 0.0

# Optional configuration for specific browser configuration
# [browser]
# Whether to run browser in headless mode (default: false)
#headless = false
# Disable browser security features (default: true)
#disable_security = true
# Extra arguments to pass to the browser
#extra_chromium_args = []
# Path to a Chrome instance to use to connect to your normal browser
# e.g. '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'
#chrome_instance_path = ""
# Connect to a browser instance via WebSocket
#wss_url = ""
# Connect to a browser instance via CDP
#cdp_url = ""

# Optional configuration, Proxy settings for the browser
# [browser.proxy]
# server = "http://proxy-server:port"
# username = "proxy-username"
# password = "proxy-password"

# Optional configuration, Search settings.
# [search]
# Search engine for agent to use. Default is "Google", can be set to "Baidu" or "DuckDuckGo" or "Bing".
#engine = "Google"
# Fallback engine order. Default is ["DuckDuckGo", "Baidu", "Bing"] - will try in this order after primary engine fails.
#fallback_engines = ["DuckDuckGo", "Baidu", "Bing"]
# Seconds to wait before retrying all engines again when they all fail due to rate limits. Default is 60.
#retry_delay = 60
# Maximum number of times to retry all engines when all fail. Default is 3.
#max_retries = 3
# Language code for search results. Options: "en" (English), "zh" (Chinese), etc.
#lang = "en"
# Country code for search results. Options: "us" (United States), "cn" (China), etc.
#country = "us"


## Sandbox configuration
#[sandbox]
#use_sandbox = false
#image = "python:3.12-slim"
#work_dir = "/workspace"
#memory_limit = "1g"  # 512m
#cpu_limit = 2.0
#timeout = 300
#network_enabled = true

# MCP (Model Context Protocol) configuration
[mcp]
server_reference = "app.mcp.server" # default server module reference

# Optional Runflow configuration
# Your can add additional agents into run-flow workflow to solve different-type tasks.
[runflow]
use_data_analysis_agent = true      # The Data Analysis Agent to solve various data analysis tasks
